name: Otomatik Test ve Dagitim (CI/CD)

on:
  push:
    branches: [ "main" ]

jobs:
  test-ve-dagit:
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Kodları Çek
      - name: Kodlari Cek (Checkout)
        uses: actions/checkout@v3

      # 2. Adım: Çelik Kasadaki Şifrelerle Docker Hub'a Giriş Yap
      - name: Docker Hub'a Giris Yap
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Adım: İmajı İnşa Et ve Docker Hub'a Fırlat!
      - name: Docker Imajini Insa Et ve Firlat (Build & Push)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-bootcamp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-bootcamp:latest